// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: great.proto

package io.grpc.justtest;

public final class Great {
  private Great() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code ResCode}
   */
  public enum ResCode
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>RES_CODE_SUCCESS = 0;</code>
     */
    RES_CODE_SUCCESS(0),
    /**
     * <code>RES_CODE_FAIL = 1;</code>
     */
    RES_CODE_FAIL(1),
    /**
     * <code>RES_CODE_NOT_LEADER = 2;</code>
     */
    RES_CODE_NOT_LEADER(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>RES_CODE_SUCCESS = 0;</code>
     */
    public static final int RES_CODE_SUCCESS_VALUE = 0;
    /**
     * <code>RES_CODE_FAIL = 1;</code>
     */
    public static final int RES_CODE_FAIL_VALUE = 1;
    /**
     * <code>RES_CODE_NOT_LEADER = 2;</code>
     */
    public static final int RES_CODE_NOT_LEADER_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ResCode valueOf(int value) {
      return forNumber(value);
    }

    public static ResCode forNumber(int value) {
      switch (value) {
        case 0: return RES_CODE_SUCCESS;
        case 1: return RES_CODE_FAIL;
        case 2: return RES_CODE_NOT_LEADER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ResCode>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ResCode> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ResCode>() {
            public ResCode findValueByNumber(int number) {
              return ResCode.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.grpc.justtest.Great.getDescriptor().getEnumTypes().get(0);
    }

    private static final ResCode[] VALUES = values();

    public static ResCode valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private ResCode(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ResCode)
  }

  /**
   * Protobuf enum {@code EntryType}
   */
  public enum EntryType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ENTRY_TYPE_DATA = 0;</code>
     */
    ENTRY_TYPE_DATA(0),
    /**
     * <code>ENTRY_TYPE_CONFIGURATION = 1;</code>
     */
    ENTRY_TYPE_CONFIGURATION(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ENTRY_TYPE_DATA = 0;</code>
     */
    public static final int ENTRY_TYPE_DATA_VALUE = 0;
    /**
     * <code>ENTRY_TYPE_CONFIGURATION = 1;</code>
     */
    public static final int ENTRY_TYPE_CONFIGURATION_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static EntryType valueOf(int value) {
      return forNumber(value);
    }

    public static EntryType forNumber(int value) {
      switch (value) {
        case 0: return ENTRY_TYPE_DATA;
        case 1: return ENTRY_TYPE_CONFIGURATION;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<EntryType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        EntryType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<EntryType>() {
            public EntryType findValueByNumber(int number) {
              return EntryType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return io.grpc.justtest.Great.getDescriptor().getEnumTypes().get(1);
    }

    private static final EntryType[] VALUES = values();

    public static EntryType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private EntryType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:EntryType)
  }

  public interface PeerOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Peer)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string host = 1;</code>
     */
    java.lang.String getHost();
    /**
     * <code>optional string host = 1;</code>
     */
    com.google.protobuf.ByteString
        getHostBytes();

    /**
     * <code>optional uint32 port = 2;</code>
     */
    int getPort();

    /**
     * <code>optional uint32 serverId = 3;</code>
     */
    int getServerId();
  }
  /**
   * Protobuf type {@code Peer}
   */
  public  static final class Peer extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Peer)
      PeerOrBuilder {
    // Use Peer.newBuilder() to construct.
    private Peer(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Peer() {
      host_ = "";
      port_ = 0;
      serverId_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Peer(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              host_ = s;
              break;
            }
            case 16: {

              port_ = input.readUInt32();
              break;
            }
            case 24: {

              serverId_ = input.readUInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.justtest.Great.internal_static_Peer_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.justtest.Great.internal_static_Peer_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.justtest.Great.Peer.class, io.grpc.justtest.Great.Peer.Builder.class);
    }

    public static final int HOST_FIELD_NUMBER = 1;
    private volatile java.lang.Object host_;
    /**
     * <code>optional string host = 1;</code>
     */
    public java.lang.String getHost() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        host_ = s;
        return s;
      }
    }
    /**
     * <code>optional string host = 1;</code>
     */
    public com.google.protobuf.ByteString
        getHostBytes() {
      java.lang.Object ref = host_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        host_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 2;
    private int port_;
    /**
     * <code>optional uint32 port = 2;</code>
     */
    public int getPort() {
      return port_;
    }

    public static final int SERVERID_FIELD_NUMBER = 3;
    private int serverId_;
    /**
     * <code>optional uint32 serverId = 3;</code>
     */
    public int getServerId() {
      return serverId_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, host_);
      }
      if (port_ != 0) {
        output.writeUInt32(2, port_);
      }
      if (serverId_ != 0) {
        output.writeUInt32(3, serverId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, host_);
      }
      if (port_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, port_);
      }
      if (serverId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, serverId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.grpc.justtest.Great.Peer)) {
        return super.equals(obj);
      }
      io.grpc.justtest.Great.Peer other = (io.grpc.justtest.Great.Peer) obj;

      boolean result = true;
      result = result && getHost()
          .equals(other.getHost());
      result = result && (getPort()
          == other.getPort());
      result = result && (getServerId()
          == other.getServerId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HOST_FIELD_NUMBER;
      hash = (53 * hash) + getHost().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort();
      hash = (37 * hash) + SERVERID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.grpc.justtest.Great.Peer parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.justtest.Great.Peer parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.justtest.Great.Peer parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.justtest.Great.Peer parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.justtest.Great.Peer parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.justtest.Great.Peer parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.justtest.Great.Peer parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.justtest.Great.Peer parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.justtest.Great.Peer parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.justtest.Great.Peer parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.justtest.Great.Peer prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Peer}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Peer)
        io.grpc.justtest.Great.PeerOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.justtest.Great.internal_static_Peer_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.justtest.Great.internal_static_Peer_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.justtest.Great.Peer.class, io.grpc.justtest.Great.Peer.Builder.class);
      }

      // Construct using io.grpc.justtest.Great.Peer.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        host_ = "";

        port_ = 0;

        serverId_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.justtest.Great.internal_static_Peer_descriptor;
      }

      public io.grpc.justtest.Great.Peer getDefaultInstanceForType() {
        return io.grpc.justtest.Great.Peer.getDefaultInstance();
      }

      public io.grpc.justtest.Great.Peer build() {
        io.grpc.justtest.Great.Peer result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.grpc.justtest.Great.Peer buildPartial() {
        io.grpc.justtest.Great.Peer result = new io.grpc.justtest.Great.Peer(this);
        result.host_ = host_;
        result.port_ = port_;
        result.serverId_ = serverId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.justtest.Great.Peer) {
          return mergeFrom((io.grpc.justtest.Great.Peer)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.justtest.Great.Peer other) {
        if (other == io.grpc.justtest.Great.Peer.getDefaultInstance()) return this;
        if (!other.getHost().isEmpty()) {
          host_ = other.host_;
          onChanged();
        }
        if (other.getPort() != 0) {
          setPort(other.getPort());
        }
        if (other.getServerId() != 0) {
          setServerId(other.getServerId());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.justtest.Great.Peer parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.justtest.Great.Peer) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object host_ = "";
      /**
       * <code>optional string host = 1;</code>
       */
      public java.lang.String getHost() {
        java.lang.Object ref = host_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          host_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string host = 1;</code>
       */
      public com.google.protobuf.ByteString
          getHostBytes() {
        java.lang.Object ref = host_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          host_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string host = 1;</code>
       */
      public Builder setHost(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        host_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string host = 1;</code>
       */
      public Builder clearHost() {
        
        host_ = getDefaultInstance().getHost();
        onChanged();
        return this;
      }
      /**
       * <code>optional string host = 1;</code>
       */
      public Builder setHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        host_ = value;
        onChanged();
        return this;
      }

      private int port_ ;
      /**
       * <code>optional uint32 port = 2;</code>
       */
      public int getPort() {
        return port_;
      }
      /**
       * <code>optional uint32 port = 2;</code>
       */
      public Builder setPort(int value) {
        
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 port = 2;</code>
       */
      public Builder clearPort() {
        
        port_ = 0;
        onChanged();
        return this;
      }

      private int serverId_ ;
      /**
       * <code>optional uint32 serverId = 3;</code>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <code>optional uint32 serverId = 3;</code>
       */
      public Builder setServerId(int value) {
        
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 serverId = 3;</code>
       */
      public Builder clearServerId() {
        
        serverId_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:Peer)
    }

    // @@protoc_insertion_point(class_scope:Peer)
    private static final io.grpc.justtest.Great.Peer DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.grpc.justtest.Great.Peer();
    }

    public static io.grpc.justtest.Great.Peer getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Peer>
        PARSER = new com.google.protobuf.AbstractParser<Peer>() {
      public Peer parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Peer(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Peer> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Peer> getParserForType() {
      return PARSER;
    }

    public io.grpc.justtest.Great.Peer getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface LogMetaDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:LogMetaData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional uint64 current_term = 1;</code>
     */
    long getCurrentTerm();

    /**
     * <code>optional uint32 voted_for = 2;</code>
     */
    int getVotedFor();

    /**
     * <code>optional uint64 first_log_index = 3;</code>
     */
    long getFirstLogIndex();

    /**
     * <code>optional uint64 commit_index = 4;</code>
     */
    long getCommitIndex();
  }
  /**
   * Protobuf type {@code LogMetaData}
   */
  public  static final class LogMetaData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:LogMetaData)
      LogMetaDataOrBuilder {
    // Use LogMetaData.newBuilder() to construct.
    private LogMetaData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private LogMetaData() {
      currentTerm_ = 0L;
      votedFor_ = 0;
      firstLogIndex_ = 0L;
      commitIndex_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private LogMetaData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              currentTerm_ = input.readUInt64();
              break;
            }
            case 16: {

              votedFor_ = input.readUInt32();
              break;
            }
            case 24: {

              firstLogIndex_ = input.readUInt64();
              break;
            }
            case 32: {

              commitIndex_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.justtest.Great.internal_static_LogMetaData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.justtest.Great.internal_static_LogMetaData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.justtest.Great.LogMetaData.class, io.grpc.justtest.Great.LogMetaData.Builder.class);
    }

    public static final int CURRENT_TERM_FIELD_NUMBER = 1;
    private long currentTerm_;
    /**
     * <code>optional uint64 current_term = 1;</code>
     */
    public long getCurrentTerm() {
      return currentTerm_;
    }

    public static final int VOTED_FOR_FIELD_NUMBER = 2;
    private int votedFor_;
    /**
     * <code>optional uint32 voted_for = 2;</code>
     */
    public int getVotedFor() {
      return votedFor_;
    }

    public static final int FIRST_LOG_INDEX_FIELD_NUMBER = 3;
    private long firstLogIndex_;
    /**
     * <code>optional uint64 first_log_index = 3;</code>
     */
    public long getFirstLogIndex() {
      return firstLogIndex_;
    }

    public static final int COMMIT_INDEX_FIELD_NUMBER = 4;
    private long commitIndex_;
    /**
     * <code>optional uint64 commit_index = 4;</code>
     */
    public long getCommitIndex() {
      return commitIndex_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (currentTerm_ != 0L) {
        output.writeUInt64(1, currentTerm_);
      }
      if (votedFor_ != 0) {
        output.writeUInt32(2, votedFor_);
      }
      if (firstLogIndex_ != 0L) {
        output.writeUInt64(3, firstLogIndex_);
      }
      if (commitIndex_ != 0L) {
        output.writeUInt64(4, commitIndex_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (currentTerm_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, currentTerm_);
      }
      if (votedFor_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, votedFor_);
      }
      if (firstLogIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, firstLogIndex_);
      }
      if (commitIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, commitIndex_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.grpc.justtest.Great.LogMetaData)) {
        return super.equals(obj);
      }
      io.grpc.justtest.Great.LogMetaData other = (io.grpc.justtest.Great.LogMetaData) obj;

      boolean result = true;
      result = result && (getCurrentTerm()
          == other.getCurrentTerm());
      result = result && (getVotedFor()
          == other.getVotedFor());
      result = result && (getFirstLogIndex()
          == other.getFirstLogIndex());
      result = result && (getCommitIndex()
          == other.getCommitIndex());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + CURRENT_TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCurrentTerm());
      hash = (37 * hash) + VOTED_FOR_FIELD_NUMBER;
      hash = (53 * hash) + getVotedFor();
      hash = (37 * hash) + FIRST_LOG_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getFirstLogIndex());
      hash = (37 * hash) + COMMIT_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCommitIndex());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.grpc.justtest.Great.LogMetaData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.justtest.Great.LogMetaData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.justtest.Great.LogMetaData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.justtest.Great.LogMetaData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.justtest.Great.LogMetaData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.justtest.Great.LogMetaData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.justtest.Great.LogMetaData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.justtest.Great.LogMetaData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.justtest.Great.LogMetaData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.justtest.Great.LogMetaData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.justtest.Great.LogMetaData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code LogMetaData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:LogMetaData)
        io.grpc.justtest.Great.LogMetaDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.justtest.Great.internal_static_LogMetaData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.justtest.Great.internal_static_LogMetaData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.justtest.Great.LogMetaData.class, io.grpc.justtest.Great.LogMetaData.Builder.class);
      }

      // Construct using io.grpc.justtest.Great.LogMetaData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        currentTerm_ = 0L;

        votedFor_ = 0;

        firstLogIndex_ = 0L;

        commitIndex_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.justtest.Great.internal_static_LogMetaData_descriptor;
      }

      public io.grpc.justtest.Great.LogMetaData getDefaultInstanceForType() {
        return io.grpc.justtest.Great.LogMetaData.getDefaultInstance();
      }

      public io.grpc.justtest.Great.LogMetaData build() {
        io.grpc.justtest.Great.LogMetaData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.grpc.justtest.Great.LogMetaData buildPartial() {
        io.grpc.justtest.Great.LogMetaData result = new io.grpc.justtest.Great.LogMetaData(this);
        result.currentTerm_ = currentTerm_;
        result.votedFor_ = votedFor_;
        result.firstLogIndex_ = firstLogIndex_;
        result.commitIndex_ = commitIndex_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.justtest.Great.LogMetaData) {
          return mergeFrom((io.grpc.justtest.Great.LogMetaData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.justtest.Great.LogMetaData other) {
        if (other == io.grpc.justtest.Great.LogMetaData.getDefaultInstance()) return this;
        if (other.getCurrentTerm() != 0L) {
          setCurrentTerm(other.getCurrentTerm());
        }
        if (other.getVotedFor() != 0) {
          setVotedFor(other.getVotedFor());
        }
        if (other.getFirstLogIndex() != 0L) {
          setFirstLogIndex(other.getFirstLogIndex());
        }
        if (other.getCommitIndex() != 0L) {
          setCommitIndex(other.getCommitIndex());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.justtest.Great.LogMetaData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.justtest.Great.LogMetaData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long currentTerm_ ;
      /**
       * <code>optional uint64 current_term = 1;</code>
       */
      public long getCurrentTerm() {
        return currentTerm_;
      }
      /**
       * <code>optional uint64 current_term = 1;</code>
       */
      public Builder setCurrentTerm(long value) {
        
        currentTerm_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 current_term = 1;</code>
       */
      public Builder clearCurrentTerm() {
        
        currentTerm_ = 0L;
        onChanged();
        return this;
      }

      private int votedFor_ ;
      /**
       * <code>optional uint32 voted_for = 2;</code>
       */
      public int getVotedFor() {
        return votedFor_;
      }
      /**
       * <code>optional uint32 voted_for = 2;</code>
       */
      public Builder setVotedFor(int value) {
        
        votedFor_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 voted_for = 2;</code>
       */
      public Builder clearVotedFor() {
        
        votedFor_ = 0;
        onChanged();
        return this;
      }

      private long firstLogIndex_ ;
      /**
       * <code>optional uint64 first_log_index = 3;</code>
       */
      public long getFirstLogIndex() {
        return firstLogIndex_;
      }
      /**
       * <code>optional uint64 first_log_index = 3;</code>
       */
      public Builder setFirstLogIndex(long value) {
        
        firstLogIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 first_log_index = 3;</code>
       */
      public Builder clearFirstLogIndex() {
        
        firstLogIndex_ = 0L;
        onChanged();
        return this;
      }

      private long commitIndex_ ;
      /**
       * <code>optional uint64 commit_index = 4;</code>
       */
      public long getCommitIndex() {
        return commitIndex_;
      }
      /**
       * <code>optional uint64 commit_index = 4;</code>
       */
      public Builder setCommitIndex(long value) {
        
        commitIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint64 commit_index = 4;</code>
       */
      public Builder clearCommitIndex() {
        
        commitIndex_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:LogMetaData)
    }

    // @@protoc_insertion_point(class_scope:LogMetaData)
    private static final io.grpc.justtest.Great.LogMetaData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.grpc.justtest.Great.LogMetaData();
    }

    public static io.grpc.justtest.Great.LogMetaData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<LogMetaData>
        PARSER = new com.google.protobuf.AbstractParser<LogMetaData>() {
      public LogMetaData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new LogMetaData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<LogMetaData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<LogMetaData> getParserForType() {
      return PARSER;
    }

    public io.grpc.justtest.Great.LogMetaData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VoteRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VoteRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 请求选票的候选人的 Id
     * </pre>
     *
     * <code>optional uint32 server_id = 1;</code>
     */
    int getServerId();

    /**
     * <pre>
     * 候选人的任期号
     * </pre>
     *
     * <code>optional uint64 term = 2;</code>
     */
    long getTerm();

    /**
     * <pre>
     * 候选人的最后日志条目的任期号
     * </pre>
     *
     * <code>optional uint64 last_log_term = 3;</code>
     */
    long getLastLogTerm();

    /**
     * <pre>
     * 候选人最后日志条目的索引值
     * </pre>
     *
     * <code>optional uint64 last_log_index = 4;</code>
     */
    long getLastLogIndex();
  }
  /**
   * Protobuf type {@code VoteRequest}
   */
  public  static final class VoteRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VoteRequest)
      VoteRequestOrBuilder {
    // Use VoteRequest.newBuilder() to construct.
    private VoteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VoteRequest() {
      serverId_ = 0;
      term_ = 0L;
      lastLogTerm_ = 0L;
      lastLogIndex_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private VoteRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              serverId_ = input.readUInt32();
              break;
            }
            case 16: {

              term_ = input.readUInt64();
              break;
            }
            case 24: {

              lastLogTerm_ = input.readUInt64();
              break;
            }
            case 32: {

              lastLogIndex_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.justtest.Great.internal_static_VoteRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.justtest.Great.internal_static_VoteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.justtest.Great.VoteRequest.class, io.grpc.justtest.Great.VoteRequest.Builder.class);
    }

    public static final int SERVER_ID_FIELD_NUMBER = 1;
    private int serverId_;
    /**
     * <pre>
     * 请求选票的候选人的 Id
     * </pre>
     *
     * <code>optional uint32 server_id = 1;</code>
     */
    public int getServerId() {
      return serverId_;
    }

    public static final int TERM_FIELD_NUMBER = 2;
    private long term_;
    /**
     * <pre>
     * 候选人的任期号
     * </pre>
     *
     * <code>optional uint64 term = 2;</code>
     */
    public long getTerm() {
      return term_;
    }

    public static final int LAST_LOG_TERM_FIELD_NUMBER = 3;
    private long lastLogTerm_;
    /**
     * <pre>
     * 候选人的最后日志条目的任期号
     * </pre>
     *
     * <code>optional uint64 last_log_term = 3;</code>
     */
    public long getLastLogTerm() {
      return lastLogTerm_;
    }

    public static final int LAST_LOG_INDEX_FIELD_NUMBER = 4;
    private long lastLogIndex_;
    /**
     * <pre>
     * 候选人最后日志条目的索引值
     * </pre>
     *
     * <code>optional uint64 last_log_index = 4;</code>
     */
    public long getLastLogIndex() {
      return lastLogIndex_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (serverId_ != 0) {
        output.writeUInt32(1, serverId_);
      }
      if (term_ != 0L) {
        output.writeUInt64(2, term_);
      }
      if (lastLogTerm_ != 0L) {
        output.writeUInt64(3, lastLogTerm_);
      }
      if (lastLogIndex_ != 0L) {
        output.writeUInt64(4, lastLogIndex_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (serverId_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, serverId_);
      }
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(2, term_);
      }
      if (lastLogTerm_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(3, lastLogTerm_);
      }
      if (lastLogIndex_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(4, lastLogIndex_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.grpc.justtest.Great.VoteRequest)) {
        return super.equals(obj);
      }
      io.grpc.justtest.Great.VoteRequest other = (io.grpc.justtest.Great.VoteRequest) obj;

      boolean result = true;
      result = result && (getServerId()
          == other.getServerId());
      result = result && (getTerm()
          == other.getTerm());
      result = result && (getLastLogTerm()
          == other.getLastLogTerm());
      result = result && (getLastLogIndex()
          == other.getLastLogIndex());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SERVER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getServerId();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + LAST_LOG_TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastLogTerm());
      hash = (37 * hash) + LAST_LOG_INDEX_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastLogIndex());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.grpc.justtest.Great.VoteRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.justtest.Great.VoteRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.justtest.Great.VoteRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.justtest.Great.VoteRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.justtest.Great.VoteRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.justtest.Great.VoteRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.justtest.Great.VoteRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.justtest.Great.VoteRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.justtest.Great.VoteRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.justtest.Great.VoteRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.justtest.Great.VoteRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VoteRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VoteRequest)
        io.grpc.justtest.Great.VoteRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.justtest.Great.internal_static_VoteRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.justtest.Great.internal_static_VoteRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.justtest.Great.VoteRequest.class, io.grpc.justtest.Great.VoteRequest.Builder.class);
      }

      // Construct using io.grpc.justtest.Great.VoteRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        serverId_ = 0;

        term_ = 0L;

        lastLogTerm_ = 0L;

        lastLogIndex_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.justtest.Great.internal_static_VoteRequest_descriptor;
      }

      public io.grpc.justtest.Great.VoteRequest getDefaultInstanceForType() {
        return io.grpc.justtest.Great.VoteRequest.getDefaultInstance();
      }

      public io.grpc.justtest.Great.VoteRequest build() {
        io.grpc.justtest.Great.VoteRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.grpc.justtest.Great.VoteRequest buildPartial() {
        io.grpc.justtest.Great.VoteRequest result = new io.grpc.justtest.Great.VoteRequest(this);
        result.serverId_ = serverId_;
        result.term_ = term_;
        result.lastLogTerm_ = lastLogTerm_;
        result.lastLogIndex_ = lastLogIndex_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.justtest.Great.VoteRequest) {
          return mergeFrom((io.grpc.justtest.Great.VoteRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.justtest.Great.VoteRequest other) {
        if (other == io.grpc.justtest.Great.VoteRequest.getDefaultInstance()) return this;
        if (other.getServerId() != 0) {
          setServerId(other.getServerId());
        }
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getLastLogTerm() != 0L) {
          setLastLogTerm(other.getLastLogTerm());
        }
        if (other.getLastLogIndex() != 0L) {
          setLastLogIndex(other.getLastLogIndex());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.justtest.Great.VoteRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.justtest.Great.VoteRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int serverId_ ;
      /**
       * <pre>
       * 请求选票的候选人的 Id
       * </pre>
       *
       * <code>optional uint32 server_id = 1;</code>
       */
      public int getServerId() {
        return serverId_;
      }
      /**
       * <pre>
       * 请求选票的候选人的 Id
       * </pre>
       *
       * <code>optional uint32 server_id = 1;</code>
       */
      public Builder setServerId(int value) {
        
        serverId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 请求选票的候选人的 Id
       * </pre>
       *
       * <code>optional uint32 server_id = 1;</code>
       */
      public Builder clearServerId() {
        
        serverId_ = 0;
        onChanged();
        return this;
      }

      private long term_ ;
      /**
       * <pre>
       * 候选人的任期号
       * </pre>
       *
       * <code>optional uint64 term = 2;</code>
       */
      public long getTerm() {
        return term_;
      }
      /**
       * <pre>
       * 候选人的任期号
       * </pre>
       *
       * <code>optional uint64 term = 2;</code>
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 候选人的任期号
       * </pre>
       *
       * <code>optional uint64 term = 2;</code>
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }

      private long lastLogTerm_ ;
      /**
       * <pre>
       * 候选人的最后日志条目的任期号
       * </pre>
       *
       * <code>optional uint64 last_log_term = 3;</code>
       */
      public long getLastLogTerm() {
        return lastLogTerm_;
      }
      /**
       * <pre>
       * 候选人的最后日志条目的任期号
       * </pre>
       *
       * <code>optional uint64 last_log_term = 3;</code>
       */
      public Builder setLastLogTerm(long value) {
        
        lastLogTerm_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 候选人的最后日志条目的任期号
       * </pre>
       *
       * <code>optional uint64 last_log_term = 3;</code>
       */
      public Builder clearLastLogTerm() {
        
        lastLogTerm_ = 0L;
        onChanged();
        return this;
      }

      private long lastLogIndex_ ;
      /**
       * <pre>
       * 候选人最后日志条目的索引值
       * </pre>
       *
       * <code>optional uint64 last_log_index = 4;</code>
       */
      public long getLastLogIndex() {
        return lastLogIndex_;
      }
      /**
       * <pre>
       * 候选人最后日志条目的索引值
       * </pre>
       *
       * <code>optional uint64 last_log_index = 4;</code>
       */
      public Builder setLastLogIndex(long value) {
        
        lastLogIndex_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 候选人最后日志条目的索引值
       * </pre>
       *
       * <code>optional uint64 last_log_index = 4;</code>
       */
      public Builder clearLastLogIndex() {
        
        lastLogIndex_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:VoteRequest)
    }

    // @@protoc_insertion_point(class_scope:VoteRequest)
    private static final io.grpc.justtest.Great.VoteRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.grpc.justtest.Great.VoteRequest();
    }

    public static io.grpc.justtest.Great.VoteRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VoteRequest>
        PARSER = new com.google.protobuf.AbstractParser<VoteRequest>() {
      public VoteRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new VoteRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VoteRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VoteRequest> getParserForType() {
      return PARSER;
    }

    public io.grpc.justtest.Great.VoteRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface VoteResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:VoteResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 当前任期号，以便于候选人去更新自己的任期号
     * </pre>
     *
     * <code>optional uint64 term = 1;</code>
     */
    long getTerm();

    /**
     * <pre>
     * 候选人赢得了此张选票时为真
     * </pre>
     *
     * <code>optional bool granted = 2;</code>
     */
    boolean getGranted();
  }
  /**
   * Protobuf type {@code VoteResponse}
   */
  public  static final class VoteResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:VoteResponse)
      VoteResponseOrBuilder {
    // Use VoteResponse.newBuilder() to construct.
    private VoteResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private VoteResponse() {
      term_ = 0L;
      granted_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private VoteResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              term_ = input.readUInt64();
              break;
            }
            case 16: {

              granted_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.justtest.Great.internal_static_VoteResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.justtest.Great.internal_static_VoteResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.justtest.Great.VoteResponse.class, io.grpc.justtest.Great.VoteResponse.Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private long term_;
    /**
     * <pre>
     * 当前任期号，以便于候选人去更新自己的任期号
     * </pre>
     *
     * <code>optional uint64 term = 1;</code>
     */
    public long getTerm() {
      return term_;
    }

    public static final int GRANTED_FIELD_NUMBER = 2;
    private boolean granted_;
    /**
     * <pre>
     * 候选人赢得了此张选票时为真
     * </pre>
     *
     * <code>optional bool granted = 2;</code>
     */
    public boolean getGranted() {
      return granted_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (term_ != 0L) {
        output.writeUInt64(1, term_);
      }
      if (granted_ != false) {
        output.writeBool(2, granted_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (term_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(1, term_);
      }
      if (granted_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, granted_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.grpc.justtest.Great.VoteResponse)) {
        return super.equals(obj);
      }
      io.grpc.justtest.Great.VoteResponse other = (io.grpc.justtest.Great.VoteResponse) obj;

      boolean result = true;
      result = result && (getTerm()
          == other.getTerm());
      result = result && (getGranted()
          == other.getGranted());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTerm());
      hash = (37 * hash) + GRANTED_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getGranted());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.grpc.justtest.Great.VoteResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.justtest.Great.VoteResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.justtest.Great.VoteResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.grpc.justtest.Great.VoteResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.grpc.justtest.Great.VoteResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.justtest.Great.VoteResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.justtest.Great.VoteResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.grpc.justtest.Great.VoteResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.grpc.justtest.Great.VoteResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.grpc.justtest.Great.VoteResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.grpc.justtest.Great.VoteResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code VoteResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:VoteResponse)
        io.grpc.justtest.Great.VoteResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.grpc.justtest.Great.internal_static_VoteResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.grpc.justtest.Great.internal_static_VoteResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.grpc.justtest.Great.VoteResponse.class, io.grpc.justtest.Great.VoteResponse.Builder.class);
      }

      // Construct using io.grpc.justtest.Great.VoteResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        term_ = 0L;

        granted_ = false;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.grpc.justtest.Great.internal_static_VoteResponse_descriptor;
      }

      public io.grpc.justtest.Great.VoteResponse getDefaultInstanceForType() {
        return io.grpc.justtest.Great.VoteResponse.getDefaultInstance();
      }

      public io.grpc.justtest.Great.VoteResponse build() {
        io.grpc.justtest.Great.VoteResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public io.grpc.justtest.Great.VoteResponse buildPartial() {
        io.grpc.justtest.Great.VoteResponse result = new io.grpc.justtest.Great.VoteResponse(this);
        result.term_ = term_;
        result.granted_ = granted_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.grpc.justtest.Great.VoteResponse) {
          return mergeFrom((io.grpc.justtest.Great.VoteResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.grpc.justtest.Great.VoteResponse other) {
        if (other == io.grpc.justtest.Great.VoteResponse.getDefaultInstance()) return this;
        if (other.getTerm() != 0L) {
          setTerm(other.getTerm());
        }
        if (other.getGranted() != false) {
          setGranted(other.getGranted());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.grpc.justtest.Great.VoteResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.grpc.justtest.Great.VoteResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long term_ ;
      /**
       * <pre>
       * 当前任期号，以便于候选人去更新自己的任期号
       * </pre>
       *
       * <code>optional uint64 term = 1;</code>
       */
      public long getTerm() {
        return term_;
      }
      /**
       * <pre>
       * 当前任期号，以便于候选人去更新自己的任期号
       * </pre>
       *
       * <code>optional uint64 term = 1;</code>
       */
      public Builder setTerm(long value) {
        
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 当前任期号，以便于候选人去更新自己的任期号
       * </pre>
       *
       * <code>optional uint64 term = 1;</code>
       */
      public Builder clearTerm() {
        
        term_ = 0L;
        onChanged();
        return this;
      }

      private boolean granted_ ;
      /**
       * <pre>
       * 候选人赢得了此张选票时为真
       * </pre>
       *
       * <code>optional bool granted = 2;</code>
       */
      public boolean getGranted() {
        return granted_;
      }
      /**
       * <pre>
       * 候选人赢得了此张选票时为真
       * </pre>
       *
       * <code>optional bool granted = 2;</code>
       */
      public Builder setGranted(boolean value) {
        
        granted_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 候选人赢得了此张选票时为真
       * </pre>
       *
       * <code>optional bool granted = 2;</code>
       */
      public Builder clearGranted() {
        
        granted_ = false;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:VoteResponse)
    }

    // @@protoc_insertion_point(class_scope:VoteResponse)
    private static final io.grpc.justtest.Great.VoteResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.grpc.justtest.Great.VoteResponse();
    }

    public static io.grpc.justtest.Great.VoteResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<VoteResponse>
        PARSER = new com.google.protobuf.AbstractParser<VoteResponse>() {
      public VoteResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new VoteResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<VoteResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<VoteResponse> getParserForType() {
      return PARSER;
    }

    public io.grpc.justtest.Great.VoteResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Peer_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Peer_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_LogMetaData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_LogMetaData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoteRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VoteRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_VoteResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_VoteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013great.proto\"4\n\004Peer\022\014\n\004host\030\001 \001(\t\022\014\n\004p" +
      "ort\030\002 \001(\r\022\020\n\010serverId\030\003 \001(\r\"e\n\013LogMetaDa" +
      "ta\022\024\n\014current_term\030\001 \001(\004\022\021\n\tvoted_for\030\002 " +
      "\001(\r\022\027\n\017first_log_index\030\003 \001(\004\022\024\n\014commit_i" +
      "ndex\030\004 \001(\004\"]\n\013VoteRequest\022\021\n\tserver_id\030\001" +
      " \001(\r\022\014\n\004term\030\002 \001(\004\022\025\n\rlast_log_term\030\003 \001(" +
      "\004\022\026\n\016last_log_index\030\004 \001(\004\"-\n\014VoteRespons" +
      "e\022\014\n\004term\030\001 \001(\004\022\017\n\007granted\030\002 \001(\010*K\n\007ResC" +
      "ode\022\024\n\020RES_CODE_SUCCESS\020\000\022\021\n\rRES_CODE_FA" +
      "IL\020\001\022\027\n\023RES_CODE_NOT_LEADER\020\002*>\n\tEntryTy",
      "pe\022\023\n\017ENTRY_TYPE_DATA\020\000\022\034\n\030ENTRY_TYPE_CO" +
      "NFIGURATION\020\00120\n\007Greeter\022%\n\004Vote\022\014.VoteR" +
      "equest\032\r.VoteResponse\"\000B\022\n\020io.grpc.justt" +
      "estb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Peer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Peer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Peer_descriptor,
        new java.lang.String[] { "Host", "Port", "ServerId", });
    internal_static_LogMetaData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_LogMetaData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_LogMetaData_descriptor,
        new java.lang.String[] { "CurrentTerm", "VotedFor", "FirstLogIndex", "CommitIndex", });
    internal_static_VoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_VoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VoteRequest_descriptor,
        new java.lang.String[] { "ServerId", "Term", "LastLogTerm", "LastLogIndex", });
    internal_static_VoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_VoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_VoteResponse_descriptor,
        new java.lang.String[] { "Term", "Granted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
