// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: great.proto

package io.grpc.justtest;

public final class JustTestProto {
  private JustTestProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_onlytest_Peer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_onlytest_Peer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_onlytest_LogMetaData_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_onlytest_LogMetaData_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_onlytest_VoteRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_onlytest_VoteRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_onlytest_VoteResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_onlytest_VoteResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013great.proto\022\010onlytest\"4\n\004Peer\022\014\n\004host\030" +
      "\001 \001(\t\022\014\n\004port\030\002 \001(\r\022\020\n\010serverId\030\003 \001(\r\"e\n" +
      "\013LogMetaData\022\024\n\014current_term\030\001 \001(\004\022\021\n\tvo" +
      "ted_for\030\002 \001(\r\022\027\n\017first_log_index\030\003 \001(\004\022\024" +
      "\n\014commit_index\030\004 \001(\004\"]\n\013VoteRequest\022\021\n\ts" +
      "erver_id\030\001 \001(\r\022\014\n\004term\030\002 \001(\004\022\025\n\rlast_log" +
      "_term\030\003 \001(\004\022\026\n\016last_log_index\030\004 \001(\004\"-\n\014V" +
      "oteResponse\022\014\n\004term\030\001 \001(\004\022\017\n\007granted\030\002 \001" +
      "(\010*K\n\007ResCode\022\024\n\020RES_CODE_SUCCESS\020\000\022\021\n\rR" +
      "ES_CODE_FAIL\020\001\022\027\n\023RES_CODE_NOT_LEADER\020\002*",
      ">\n\tEntryType\022\023\n\017ENTRY_TYPE_DATA\020\000\022\034\n\030ENT" +
      "RY_TYPE_CONFIGURATION\020\0012B\n\007Greeter\0227\n\004Vo" +
      "te\022\025.onlytest.VoteRequest\032\026.onlytest.Vot" +
      "eResponse\"\000B(\n\020io.grpc.justtestB\rJustTes" +
      "tProtoP\001\242\002\002WYb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_onlytest_Peer_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_onlytest_Peer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_onlytest_Peer_descriptor,
        new java.lang.String[] { "Host", "Port", "ServerId", });
    internal_static_onlytest_LogMetaData_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_onlytest_LogMetaData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_onlytest_LogMetaData_descriptor,
        new java.lang.String[] { "CurrentTerm", "VotedFor", "FirstLogIndex", "CommitIndex", });
    internal_static_onlytest_VoteRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_onlytest_VoteRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_onlytest_VoteRequest_descriptor,
        new java.lang.String[] { "ServerId", "Term", "LastLogTerm", "LastLogIndex", });
    internal_static_onlytest_VoteResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_onlytest_VoteResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_onlytest_VoteResponse_descriptor,
        new java.lang.String[] { "Term", "Granted", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
