// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: great.proto

package io.grpc.justtest;

public interface LogMetaDataOrBuilder extends
    // @@protoc_insertion_point(interface_extends:onlytest.LogMetaData)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional uint64 current_term = 1;</code>
   */
  long getCurrentTerm();

  /**
   * <code>optional uint32 voted_for = 2;</code>
   */
  int getVotedFor();

  /**
   * <code>optional uint64 first_log_index = 3;</code>
   */
  long getFirstLogIndex();

  /**
   * <code>optional uint64 commit_index = 4;</code>
   */
  long getCommitIndex();
}
