// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: great.proto

package io.grpc.justtest;

public interface PeerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:onlytest.Peer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional string host = 1;</code>
   */
  java.lang.String getHost();
  /**
   * <code>optional string host = 1;</code>
   */
  com.google.protobuf.ByteString
      getHostBytes();

  /**
   * <code>optional uint32 port = 2;</code>
   */
  int getPort();

  /**
   * <code>optional uint32 serverId = 3;</code>
   */
  int getServerId();
}
