// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: great.proto

package io.grpc.justtest;

public interface VoteRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:onlytest.VoteRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 请求选票的候选人的 Id
   * </pre>
   *
   * <code>optional uint32 server_id = 1;</code>
   */
  int getServerId();

  /**
   * <pre>
   * 候选人的任期号
   * </pre>
   *
   * <code>optional uint64 term = 2;</code>
   */
  long getTerm();

  /**
   * <pre>
   * 候选人的最后日志条目的任期号
   * </pre>
   *
   * <code>optional uint64 last_log_term = 3;</code>
   */
  long getLastLogTerm();

  /**
   * <pre>
   * 候选人最后日志条目的索引值
   * </pre>
   *
   * <code>optional uint64 last_log_index = 4;</code>
   */
  long getLastLogIndex();
}
