// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: great.proto

package io.grpc.justtest;

/**
 * Protobuf type {@code onlytest.VoteRequest}
 */
public  final class VoteRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:onlytest.VoteRequest)
    VoteRequestOrBuilder {
  // Use VoteRequest.newBuilder() to construct.
  private VoteRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private VoteRequest() {
    serverId_ = 0;
    term_ = 0L;
    lastLogTerm_ = 0L;
    lastLogIndex_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private VoteRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            serverId_ = input.readUInt32();
            break;
          }
          case 16: {

            term_ = input.readUInt64();
            break;
          }
          case 24: {

            lastLogTerm_ = input.readUInt64();
            break;
          }
          case 32: {

            lastLogIndex_ = input.readUInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return io.grpc.justtest.JustTestProto.internal_static_onlytest_VoteRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return io.grpc.justtest.JustTestProto.internal_static_onlytest_VoteRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            io.grpc.justtest.VoteRequest.class, io.grpc.justtest.VoteRequest.Builder.class);
  }

  public static final int SERVER_ID_FIELD_NUMBER = 1;
  private int serverId_;
  /**
   * <pre>
   * 请求选票的候选人的 Id
   * </pre>
   *
   * <code>optional uint32 server_id = 1;</code>
   */
  public int getServerId() {
    return serverId_;
  }

  public static final int TERM_FIELD_NUMBER = 2;
  private long term_;
  /**
   * <pre>
   * 候选人的任期号
   * </pre>
   *
   * <code>optional uint64 term = 2;</code>
   */
  public long getTerm() {
    return term_;
  }

  public static final int LAST_LOG_TERM_FIELD_NUMBER = 3;
  private long lastLogTerm_;
  /**
   * <pre>
   * 候选人的最后日志条目的任期号
   * </pre>
   *
   * <code>optional uint64 last_log_term = 3;</code>
   */
  public long getLastLogTerm() {
    return lastLogTerm_;
  }

  public static final int LAST_LOG_INDEX_FIELD_NUMBER = 4;
  private long lastLogIndex_;
  /**
   * <pre>
   * 候选人最后日志条目的索引值
   * </pre>
   *
   * <code>optional uint64 last_log_index = 4;</code>
   */
  public long getLastLogIndex() {
    return lastLogIndex_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (serverId_ != 0) {
      output.writeUInt32(1, serverId_);
    }
    if (term_ != 0L) {
      output.writeUInt64(2, term_);
    }
    if (lastLogTerm_ != 0L) {
      output.writeUInt64(3, lastLogTerm_);
    }
    if (lastLogIndex_ != 0L) {
      output.writeUInt64(4, lastLogIndex_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (serverId_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt32Size(1, serverId_);
    }
    if (term_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(2, term_);
    }
    if (lastLogTerm_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, lastLogTerm_);
    }
    if (lastLogIndex_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(4, lastLogIndex_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof io.grpc.justtest.VoteRequest)) {
      return super.equals(obj);
    }
    io.grpc.justtest.VoteRequest other = (io.grpc.justtest.VoteRequest) obj;

    boolean result = true;
    result = result && (getServerId()
        == other.getServerId());
    result = result && (getTerm()
        == other.getTerm());
    result = result && (getLastLogTerm()
        == other.getLastLogTerm());
    result = result && (getLastLogIndex()
        == other.getLastLogIndex());
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + SERVER_ID_FIELD_NUMBER;
    hash = (53 * hash) + getServerId();
    hash = (37 * hash) + TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTerm());
    hash = (37 * hash) + LAST_LOG_TERM_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastLogTerm());
    hash = (37 * hash) + LAST_LOG_INDEX_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getLastLogIndex());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static io.grpc.justtest.VoteRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.justtest.VoteRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.justtest.VoteRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static io.grpc.justtest.VoteRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static io.grpc.justtest.VoteRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.justtest.VoteRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.justtest.VoteRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static io.grpc.justtest.VoteRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static io.grpc.justtest.VoteRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static io.grpc.justtest.VoteRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(io.grpc.justtest.VoteRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code onlytest.VoteRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:onlytest.VoteRequest)
      io.grpc.justtest.VoteRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.grpc.justtest.JustTestProto.internal_static_onlytest_VoteRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.grpc.justtest.JustTestProto.internal_static_onlytest_VoteRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.grpc.justtest.VoteRequest.class, io.grpc.justtest.VoteRequest.Builder.class);
    }

    // Construct using io.grpc.justtest.VoteRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      serverId_ = 0;

      term_ = 0L;

      lastLogTerm_ = 0L;

      lastLogIndex_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return io.grpc.justtest.JustTestProto.internal_static_onlytest_VoteRequest_descriptor;
    }

    public io.grpc.justtest.VoteRequest getDefaultInstanceForType() {
      return io.grpc.justtest.VoteRequest.getDefaultInstance();
    }

    public io.grpc.justtest.VoteRequest build() {
      io.grpc.justtest.VoteRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public io.grpc.justtest.VoteRequest buildPartial() {
      io.grpc.justtest.VoteRequest result = new io.grpc.justtest.VoteRequest(this);
      result.serverId_ = serverId_;
      result.term_ = term_;
      result.lastLogTerm_ = lastLogTerm_;
      result.lastLogIndex_ = lastLogIndex_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof io.grpc.justtest.VoteRequest) {
        return mergeFrom((io.grpc.justtest.VoteRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(io.grpc.justtest.VoteRequest other) {
      if (other == io.grpc.justtest.VoteRequest.getDefaultInstance()) return this;
      if (other.getServerId() != 0) {
        setServerId(other.getServerId());
      }
      if (other.getTerm() != 0L) {
        setTerm(other.getTerm());
      }
      if (other.getLastLogTerm() != 0L) {
        setLastLogTerm(other.getLastLogTerm());
      }
      if (other.getLastLogIndex() != 0L) {
        setLastLogIndex(other.getLastLogIndex());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      io.grpc.justtest.VoteRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (io.grpc.justtest.VoteRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int serverId_ ;
    /**
     * <pre>
     * 请求选票的候选人的 Id
     * </pre>
     *
     * <code>optional uint32 server_id = 1;</code>
     */
    public int getServerId() {
      return serverId_;
    }
    /**
     * <pre>
     * 请求选票的候选人的 Id
     * </pre>
     *
     * <code>optional uint32 server_id = 1;</code>
     */
    public Builder setServerId(int value) {
      
      serverId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 请求选票的候选人的 Id
     * </pre>
     *
     * <code>optional uint32 server_id = 1;</code>
     */
    public Builder clearServerId() {
      
      serverId_ = 0;
      onChanged();
      return this;
    }

    private long term_ ;
    /**
     * <pre>
     * 候选人的任期号
     * </pre>
     *
     * <code>optional uint64 term = 2;</code>
     */
    public long getTerm() {
      return term_;
    }
    /**
     * <pre>
     * 候选人的任期号
     * </pre>
     *
     * <code>optional uint64 term = 2;</code>
     */
    public Builder setTerm(long value) {
      
      term_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 候选人的任期号
     * </pre>
     *
     * <code>optional uint64 term = 2;</code>
     */
    public Builder clearTerm() {
      
      term_ = 0L;
      onChanged();
      return this;
    }

    private long lastLogTerm_ ;
    /**
     * <pre>
     * 候选人的最后日志条目的任期号
     * </pre>
     *
     * <code>optional uint64 last_log_term = 3;</code>
     */
    public long getLastLogTerm() {
      return lastLogTerm_;
    }
    /**
     * <pre>
     * 候选人的最后日志条目的任期号
     * </pre>
     *
     * <code>optional uint64 last_log_term = 3;</code>
     */
    public Builder setLastLogTerm(long value) {
      
      lastLogTerm_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 候选人的最后日志条目的任期号
     * </pre>
     *
     * <code>optional uint64 last_log_term = 3;</code>
     */
    public Builder clearLastLogTerm() {
      
      lastLogTerm_ = 0L;
      onChanged();
      return this;
    }

    private long lastLogIndex_ ;
    /**
     * <pre>
     * 候选人最后日志条目的索引值
     * </pre>
     *
     * <code>optional uint64 last_log_index = 4;</code>
     */
    public long getLastLogIndex() {
      return lastLogIndex_;
    }
    /**
     * <pre>
     * 候选人最后日志条目的索引值
     * </pre>
     *
     * <code>optional uint64 last_log_index = 4;</code>
     */
    public Builder setLastLogIndex(long value) {
      
      lastLogIndex_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * 候选人最后日志条目的索引值
     * </pre>
     *
     * <code>optional uint64 last_log_index = 4;</code>
     */
    public Builder clearLastLogIndex() {
      
      lastLogIndex_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:onlytest.VoteRequest)
  }

  // @@protoc_insertion_point(class_scope:onlytest.VoteRequest)
  private static final io.grpc.justtest.VoteRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new io.grpc.justtest.VoteRequest();
  }

  public static io.grpc.justtest.VoteRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<VoteRequest>
      PARSER = new com.google.protobuf.AbstractParser<VoteRequest>() {
    public VoteRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new VoteRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<VoteRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<VoteRequest> getParserForType() {
    return PARSER;
  }

  public io.grpc.justtest.VoteRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

