// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: great.proto

package io.grpc.justtest;

public interface VoteResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:onlytest.VoteResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 当前任期号，以便于候选人去更新自己的任期号
   * </pre>
   *
   * <code>optional uint64 term = 1;</code>
   */
  long getTerm();

  /**
   * <pre>
   * 候选人赢得了此张选票时为真
   * </pre>
   *
   * <code>optional bool granted = 2;</code>
   */
  boolean getGranted();
}
